### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yuka3prgrm** [yuka3prgrm/protospace-39446#1]
https://protospace-39446.onrender.com

よろしくお願いいたします！

**Comment by shodai-ito** [comment]
@yuka3prgrm さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
細かな部分になりますが、「こんにちは」の後のユーザー名には、敬称まで記載をお願いいたします。

- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
現在、編集後にトップページに遷移する仕様になっております。
詳細ページに遷移するように実装をお願いいたします。

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
ログアウト状態でも新規投稿ページに遷移できてしまいました。
編集ページに遷移しようとした時と同様、ログインページにリダイレクトされるようにしましょう！
【チェック方法】
最初にログアウト状態を作る。投稿ページ・編集ページのURLを打ち込み、ログインページにリダイレクトされれば正常な挙動。

- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
ログアウト状態ではユーザー詳細ページに遷移できないようになっています。
ユーザ詳細ページにも遷移できるようにしましょう！

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yuka3prgrm** [comment]
修正いたしました。よろしくお願いいたします。！

**Comment by shodai-ito** [comment]
@yuka3prgrm さん、再度ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by yuka3prgrm** [comment]
とてもうれしいです！！！
ありがとうございます！！＾＾
